services:
  js2go:
    container_name: js2go
    image: ghcr.io/mikhail-angelov/playground/playground:latest
    restart: unless-stopped
    networks:
      - proxy-net
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./.env
    labels:
      monic.enabled: "true"
      monic.check: "http"
      monic.check_http_url: "https://js2go.ru"
      monic.name: "js2go"
      redoproxy.enabled: "true"
      redoproxy.domain: "js2go.ru"
      redoproxy.port: 5000
    command: npm start
    volumes:
      - ./database.db:/app/database.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  proxy-net:
    external: true